---
# Configure nginx
- name: Check if the nginx default site conf exists
  stat:
    path: /etc/nginx/sites-enabled/default
  register: cfg_ngx_default

- name: Move sites-enabled/default to sites-disabled
  shell: |
    mkdir -p /etc/nginx/sites-disabled/default
    mv /etc/nginx/sites-enabled/default /etc/nginx/sites-disabled/default
  when: cfg_ngx_default.stat.exists

- name: Generate nginx configuration file
  template: 
    src: nginx.conf.j2 
    dest: /etc/nginx/nginx.conf
    validate: nginx -t -c %s
  register: ngx_cfg_rendered

- name: Reload nginx service
  service: name=nginx state=restarted
  when: ngx_cfg_rendered.changed == true
